DROP TABLE IF EXISTS ALBUM;

CREATE TABLE IF NOT EXISTS ALBUM (
    id INTEGER  PRIMARY KEY AUTO_INCREMENT,
    nom VARCHAR2(100),
    artiste VARCHAR2(100),
    genre VARCHAR2(100),
    description VARCHAR2(500),
    url_Image VARCHAR2(1000)
);