spring:
  datasource:
    url: "jdbc:h2:mem:albumdb"
    username: sa
    password: 
    schema:
    - classpath:album-schema.sql
    data:
    - classpath:album-data.sql
    
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
logging:
  level:
    root: ERROR
    "[fr.formation.concert.domain]": DEBUG
    "[org.springframework]": INFO
    "[org.springframework.web]": ERROR
    "[org.springframework.boot.autoconfigure.h2]": DEBUG
    "[org.hibernate]": ERROR